name: Build / Test
on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v4
              with:
                 python-version: '3.9'
                
            - run: pip install -r requirements.txt
            - run: python main.py